### ISSUE TITLE
expand source file sidebar

### ISSUE THREAD

**Issue by MarekHohmann** [JanMalch/ermine#1]
When you extend a folder in the left Sidebar, it would be nice if the Sidebar would be set to the correct size automatically.

![image](https://user-images.githubusercontent.com/31142377/57616245-eda6bc80-757d-11e9-8592-946262cfa058.png)

**Comment by JanMalch** [comment]
Double clicking on the drag sizer now auto-adjusts the width.

>70d2eb86d671a82798e48db0a328554ec9ad5293
